release:
  prerelease: true

builds:
  - binary: bashful
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}} -X main.BuildTime={{.Date}}`.

archive:
  format: binary

fpm:
  license: MIT
  homepage: https://github.com/wagoodman/bashful/
  formats:
    - deb
    - rpm

brew:
  github:
    owner: wagoodman
    name: homebrew-bashful
